type: custom:apexcharts-card
graph_span: 7d
span:
  end: day
header:
  title: Weekly Balance (kWh)
  show: true
apex_config:
  chart:
    stacked: true
    stackType: normal
    animations:
      enabled: false
series:
  - entity: sensor.ec_produced_energy_day
    name: Production
    color: rgba(233, 188, 5, 1)
    type: column
    stack_group: energy
    group_by: { func: max, duration: 1d, fill: zero }
    show: { in_legend: true, legend_value: false, in_chart: true }

  - entity: sensor.ec_imported_residual_energy_day
    name: Imported
    color: rgba(0, 128, 255, 1)
    type: column
    stack_group: energy
    group_by: { func: max, duration: 1d, fill: zero }
    show: { in_legend: true, legend_value: false, in_chart: true }

  - entity: sensor.ec_exported_residual_energy_day
    name: Returned
    color: rgba(127, 17, 224, 1)
    type: column
    stack_group: energy
    transform: |
      if (x === null || x === undefined || isNaN(x)) return null;
      return x * -1;
    group_by: { func: max, duration: 1d, fill: zero }
    show: { in_legend: true, legend_value: false, in_chart: true }

  - entity: sensor.ec_battery_discharge_energy_day
    name: Battery Discharge
    color: rgba(52, 168, 83, 1)
    type: column
    stack_group: energy
    group_by: { func: max, duration: 1d, fill: zero }
    show: { in_legend: true, legend_value: false, in_chart: true }

  - entity: sensor.ec_battery_charge_energy_day
    name: Battery Charge
    color: rgba(34, 139, 34, 0.7)
    type: column
    stack_group: energy
    transform: |
      if (x === null || x === undefined || isNaN(x)) return null;
      return x * -1;
    group_by: { func: max, duration: 1d, fill: zero }
    show: { in_legend: true, legend_value: false, in_chart: true }
